 <!DOCTYPE html>
 <html>
 <head>
	<title>Codeigniter Shopping Cart</title>
	<link href="<?php echo base_url();?>assets/css/core.css" media="screen" rel="stylesheet" type="text/css"/>
	<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery-1.6.2.min.js"></script>
	<script type="text/javascript" src="<?php echo base_url();?>assets/js/core.js"></script>
 </head>
 <body>
	<!-- This is page generated by /views/index.php-->
	<div id="wrap">
		<?php 
			//This $content is comming from Controller
			//and it populated in model
			$this->view($content);
		?>
		<div class="cart_list">
			<h3>Your shopping list</h3>
			<div id="cart_content">
				<?php 
					echo $this->view('cart/cart.php');
				?>
			</div>
		</div>
	</div>
 </body>
 </html>